### PR TITLE
Command line log enabling

### PR DESCRIPTION
**Pull request by chestnykh**
I've implemented log enabling as cmd argument.
Now if you run ```./minichem --logfile=log_file``` 
or ```./minichem -llog_file``` or ```./minichem -l log_file```
the log will be ```log_file```.
If ```argc == 1``` log will be set to default ```minichem.log```

### CODE REVIEW

**Comment by chestnykh** [comment]
There are a lot of commits in one pull request, I'm sorry, I've tried to create a number of pull requests but...)

**Comment by aoleynichenko** [comment]
Добавь себя в разработчики в outputHeader(). С уважением,Шурик 07.11.2016, 13:08, "Dmitriy" notifications@github.com:There are a lot of commits in one pull request, I'm sorry, I've tried to create a number of pull requests but...)—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by aoleynichenko** [comment]
Dmitry, thank for your add-ons!

**Comment by aoleynichenko** [comment]
I will rewrite your comments in English :) I hope minichem has a great international future :)

**Pull request merged**
